project_name: my-go-project

builds:
  - id: my-go-linux-binary
    main: ./cmd/main.go  # Adjust to your main Go entry point
    goos:
      - linux            # ✅ Only build for Linux
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

release:
  github:
    owner: your-github-username
    name: your-repo-name